# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mark < Formula
  desc "Sync your markdown files with Confluence pages."
  homepage "https://github.com/kovetskiy/mark"
  version "15.5.0"
  license "Apache 2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kovetskiy/mark/releases/download/v15.5.0/mark_Darwin_x86_64.tar.gz"
      sha256 "7c3c327aecc402aca1b5f66d710d86a48d25b644bd32553b094bc6f5751bc7e5"

      define_method(:install) do
        bin.install "mark"
        generate_completions_from_executable(bin/"mark", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kovetskiy/mark/releases/download/v15.5.0/mark_Darwin_arm64.tar.gz"
      sha256 "65258f1adb2ae03f9292112e4984b9482cb54cbc1288ad7d89c39ba383845fce"

      define_method(:install) do
        bin.install "mark"
        generate_completions_from_executable(bin/"mark", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kovetskiy/mark/releases/download/v15.5.0/mark_Linux_x86_64.tar.gz"
      sha256 "5a64a67ee0330c21485d834e8ec5e841564b3604960ccaadbfdeb09c3e479c25"
      define_method(:install) do
        bin.install "mark"
        generate_completions_from_executable(bin/"mark", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kovetskiy/mark/releases/download/v15.5.0/mark_Linux_arm64.tar.gz"
      sha256 "d1874a3a90dd2a5bf24965a64dd8f9ee6365f68cff1fbe1b827157faa75660fd"
      define_method(:install) do
        bin.install "mark"
        generate_completions_from_executable(bin/"mark", "completion")
      end
    end
  end

  test do
    system "#{bin}/mark", "version"
  end
end
