# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mark < Formula
  desc "Sync your markdown files with Confluence pages."
  homepage "https://github.com/kovetskiy/mark"
  version "16.17.1"
  license "Apache 2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kovetskiy/mark/releases/download/v16.17.1/mark_Darwin_x86_64.tar.gz"
      sha256 "bc67cd089416617e353526eb972f59732f96c2f106f7ec2a722a2e003f6a1e1b"

      define_method(:install) do
        bin.install "mark"
        generate_completions_from_executable(bin/"mark", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kovetskiy/mark/releases/download/v16.17.1/mark_Darwin_arm64.tar.gz"
      sha256 "a49456e9c336c60898813f8f922c78cb89b20e5a0d2ff7c82c962e573ee1839b"

      define_method(:install) do
        bin.install "mark"
        generate_completions_from_executable(bin/"mark", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kovetskiy/mark/releases/download/v16.17.1/mark_Linux_x86_64.tar.gz"
      sha256 "d270c4f39f329880f1c565dbdcd94d8613dd559db692d44a917faffcf3c53a08"
      define_method(:install) do
        bin.install "mark"
        generate_completions_from_executable(bin/"mark", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kovetskiy/mark/releases/download/v16.17.1/mark_Linux_arm64.tar.gz"
      sha256 "703770278c72c2ddf704d8cccc1628afd05551b62fd295cc19e03da013cbb4f1"
      define_method(:install) do
        bin.install "mark"
        generate_completions_from_executable(bin/"mark", "completion")
      end
    end
  end

  test do
    system "#{bin}/mark", "version"
  end
end
