# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mark < Formula
  desc "Sync your markdown files with Confluence pages."
  homepage "https://github.com/kovetskiy/mark"
  version "16.19.1"
  license "Apache 2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kovetskiy/mark/releases/download/v16.19.1/mark_Darwin_x86_64.tar.gz"
      sha256 "d7331cb3e7fb892809b5c69eb3550cfcd40d7fa6b4706993a3c15df949f15477"

      define_method(:install) do
        bin.install "mark"
        generate_completions_from_executable(bin/"mark", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kovetskiy/mark/releases/download/v16.19.1/mark_Darwin_arm64.tar.gz"
      sha256 "ea9cf9d2a3f72f18cedf130007a12291458c4d176b4cb515fbff3ce46eac8f3b"

      define_method(:install) do
        bin.install "mark"
        generate_completions_from_executable(bin/"mark", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kovetskiy/mark/releases/download/v16.19.1/mark_Linux_x86_64.tar.gz"
      sha256 "5f540b7aea51648195bdd69c9df552eac90bbb074aa88979376bfcb01e3eb49c"
      define_method(:install) do
        bin.install "mark"
        generate_completions_from_executable(bin/"mark", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kovetskiy/mark/releases/download/v16.19.1/mark_Linux_arm64.tar.gz"
      sha256 "a62a805b43ec289eee4cb1b0eebeb9ee0d7936ccee0ccb7a14a67d0cd6b4ee9a"
      define_method(:install) do
        bin.install "mark"
        generate_completions_from_executable(bin/"mark", "completion")
      end
    end
  end

  test do
    system "#{bin}/mark", "version"
  end
end
